# Generated by Django 5.2.13 on 2026-05-03 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('anthropic', 'Anthropic')], default='ollama', max_length=20)),
                ('ollama_base_url', models.CharField(default='http://localhost:11434', max_length=500)),
                ('ollama_model', models.CharField(default='llama3', max_length=100)),
                ('openai_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('openai_model', models.CharField(default='gpt-4o', max_length=100)),
                ('gemini_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('gemini_model', models.CharField(default='gemini-1.5-pro', max_length=100)),
                ('anthropic_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('anthropic_model', models.CharField(default='claude-3-5-sonnet-20241022', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AI Settings',
                'db_table': 'tracker_ai_settings',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone_screen', 'Phone Screen'), ('technical', 'Technical'), ('hr', 'HR'), ('on_site', 'On Site'), ('final_round', 'Final Round'), ('take_home', 'Take Home'), ('other', 'Other')], max_length=20)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, choices=[('video', 'Video'), ('phone', 'Phone'), ('in_person', 'In Person'), ('take_home', 'Take Home')], max_length=20, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('interviewer_role', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('outcome', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('pending', 'Pending'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('follow_up_sent', models.BooleanField(default=False)),
                ('prep_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('ready', 'Ready')], default='not_started', max_length=20)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_interviews',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_notes', models.TextField(blank=True, null=True)),
                ('went_well', models.TextField(blank=True, null=True)),
                ('improve', models.TextField(blank=True, null=True)),
                ('dont_repeat', models.TextField(blank=True, null=True)),
                ('key_learnings', models.TextField(blank=True, null=True)),
                ('self_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('would_prepare_differently', models.BooleanField(null=True)),
                ('prepare_differently_note', models.TextField(blank=True, null=True)),
                ('company_impression', models.TextField(blank=True, null=True)),
                ('salary_discussed', models.BooleanField(default=False)),
                ('salary_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tracker.interview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interview Notes',
                'db_table': 'tracker_interview_notes',
            },
        ),
        migrations.CreateModel(
            name='InterviewPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics_to_study', models.JSONField(default=list)),
                ('questions_to_ask', models.TextField(blank=True, null=True)),
                ('questions_expected', models.TextField(blank=True, null=True)),
                ('checklist', models.JSONField(default=list)),
                ('useful_links', models.JSONField(default=list)),
                ('free_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prep', to='tracker.interview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interview Preps',
                'db_table': 'tracker_interview_prep',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('technical', 'Technical'), ('hr_interview', 'HR Interview'), ('final_round', 'Final Round'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived')], default='applied', max_length=30)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('date_applied', models.DateField()),
                ('source', models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('direct', 'Direct'), ('job_board', 'Job Board'), ('recruiter', 'Recruiter'), ('other', 'Other')], max_length=20, null=True)),
                ('next_step', models.TextField(blank=True, null=True)),
                ('next_interview_date', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resume_version', models.CharField(blank=True, max_length=100, null=True)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_job_applications',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='tracker.jobapplication'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('interview', 'Interview'), ('follow_up', 'Follow Up'), ('deadline', 'Deadline'), ('prep_session', 'Prep Session'), ('custom', 'Custom')], max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='tracker.interview')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='tracker.jobapplication')),
            ],
            options={
                'db_table': 'tracker_calendar_events',
                'ordering': ['start_at'],
            },
        ),
    ]
